"""Strategy modules — imported to trigger @register side effects."""

from . import (  # noqa: F401
    brugada_huca,
    challenge2020,
    challenge2021,
    chapman,
    code15,
    code_test,
    cpsc_2018,
    ecg_arrhythmia,
    ecgcipa,
    ecgdmmld,
    ecgrdvq,
    echonext,
    generic,
    ikem,
    incartdb,
    leipzig_heart_center_ecg,
    ludb,
    mhd_effect_ecg_mri,
    mimic_iv_ecg,
    mimic_iv_ecg_demo,
    ningbo_iva,
    norwegian_athlete_ecg,
    ptbdb,
    ptbxl,
    sami_trop,
    sph,
    staffiii,
    wctecgdb,
    zzu_pecg,
)
